language: julia

os:
  - linux

julia:
  - 0.6
  - 0.7

matrix:
  fast_finish: true
  allow_failures:
    - julia: 0.7

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Bootstrap"); Pkg.test("Bootstrap"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("Bootstrap")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder(), flags="julia_$(VERSION.major)_$(VERSION.minor)")'
