site_name: Bootstrap.jl

site_description: Bootstrapping statistic framework for the Julia programming language

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

repo_url: https://github.com/juliangehring/Bootstrap.jl

pages:
- Introduction: 'index.md'
- Library: 'library.md'
- License: 'LICENSE.md'

site_favicon: null

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - codehilite
  - def_list  
  - extra
  - tables
  - fenced_code

docs_dir: 'build'
